// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIefb8ZprgeyQUFiqF_85wJEfSOAUNxjE',
    appId: '1:700419981635:web:6e3fd5110e22f1b0766ff6',
    messagingSenderId: '700419981635',
    projectId: 'the-mechanic-47aec',
    authDomain: 'the-mechanic-47aec.firebaseapp.com',
    databaseURL: 'https://the-mechanic-47aec-default-rtdb.firebaseio.com',
    storageBucket: 'the-mechanic-47aec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAR4FSxfzX0DIfxJkyPraoMSIQTQ1jer4o',
    appId: '1:700419981635:android:a0a5fb1f0cdab077766ff6',
    messagingSenderId: '700419981635',
    projectId: 'the-mechanic-47aec',
    databaseURL: 'https://the-mechanic-47aec-default-rtdb.firebaseio.com',
    storageBucket: 'the-mechanic-47aec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCePiUWvCUZhNvj6MnxljUyduBMUyLiWzk',
    appId: '1:700419981635:ios:5508b0130f1f6397766ff6',
    messagingSenderId: '700419981635',
    projectId: 'the-mechanic-47aec',
    databaseURL: 'https://the-mechanic-47aec-default-rtdb.firebaseio.com',
    storageBucket: 'the-mechanic-47aec.appspot.com',
    androidClientId: '700419981635-30q2kiosstka4udeoguv2qi81pmce852.apps.googleusercontent.com',
    iosClientId: '700419981635-ee6lgglle17ilk2bk0tlbkosscgb8kk6.apps.googleusercontent.com',
    iosBundleId: 'car.mechanic.the',
  );
}
